Create DATABASE NOTAGEST;

USE NOTAGEST;
 
CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL
);


CREATE TABLE IMOVEL(
    ID_IMOVEL INT PRIMARY KEY IDENTITY,
	LOGRADOURO VARCHAR(50),
	NUMERO INT,
    COMPLEMENTO VARCHAR(20),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(40),
    ESTADO VARCHAR(35),
	TIPO_IMOVEL VARCHAR(50)
);

CREATE TABLE DOCUMENTO(
	ID_DOCUMENTO INT PRIMARY KEY IDENTITY,
	TITULO VARCHAR(50),
	CATEGORIA INT,
	DATA_UPLOAD DATETIME,
	SUB_CATEGORIA INT,
	OBSERVACAO TEXT,
	VALOR DECIMAL(10,2),
    ARQUIVO VARCHAR(100),
	ID_USUARIO INT NOT NULL,
	CONSTRAINT FK_ID_USUARIO_DOCUMENTO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE TEMIMOVEL (
	ID_DOC INT NOT NULL,
	ID_IMOVEL INT NOT NULL,
	CONSTRAINT FK_ID_DOCUMENTO FOREIGN KEY (ID_DOC) REFERENCES DOCUMENTO(ID_DOCUMENTO),
	CONSTRAINT FK_ID_IMOVEL FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL(ID_IMOVEL)
)

CREATE TABLE LOG_USUARIO(
    ID_LOG INT PRIMARY KEY IDENTITY,
    DATA_HORA DATETIME NOT NULL,
    ACAO VARCHAR(70),
    DATA_UPLOAD DATETIME,
	ID_USUARIO INT NOT NULL
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);